version: "2"
run:
  go: "1.23"
  tests: true
  allow-parallel-runners: true
  allow-serial-runners: true
linters:
  default: all
  disable:
    - bodyclose
    - depguard
    - exhaustruct
    - forcetypeassert
    - ireturn
    - mnd
    - nlreturn
    - wrapcheck
    - wsl
  settings:
    dupl:
      threshold: 250
    errorlint:
      comparison: false
    funlen:
      lines: 150
    gosec:
      excludes:
        - G404
    lll:
      line-length: 180
    revive:
      rules:
        - name: var-naming
          arguments:
            - - IDS
    varnamelen:
      min-name-length: 1
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofumpt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
